site_name: BEP
theme:
  name: material
  language: zh
  #  font: false
  font:
    text: Microsoft YaHei
plugins:
  - open-in-new-tab
  - search

site_dir: public

repo_url: https://github.com/trim21/bep-zh/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
