on:
  push:


jobs:
  build:
    permissions:
      contents: write
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      - run: pip install -r requirements.txt

      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
